# This is my Dev version of my docker-compose.yml
services:
  mlm-web-server:
    build:
      context: .
      target: build  # <--- FIX: This tells Docker to stop at Stage 1 (with Maven installed)

  # Keep container running so VS Code can attach
    entrypoint: ["sh", "-c", "tail -f /dev/null"]

    volumes:
      - .:/app       # <--- FIX: This saves your code edits to Windows