spring.application.name=mlm
server.port=8080
# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://aws-postgresql.cst8y4iucesv.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=require
spring.datasource.username=brudow
spring.datasource.password=LinusTorvalds01001
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JMX Actuator Endpoints for Dev environment
spring.jmx.enabled=true
management.endpoints.jmx.exposure.include=*
