# spring.application.name=mlm
# server.port=8080

# Moved these to docker-compose.yml
# PostgreSQL Configuration
# spring.datasource.url=${DB_STRING}
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASS}
# spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JMX Actuator Endpoints for Dev environment
# spring.jmx.enabled=true
# management.endpoints.jmx.exposure.include=*
